from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt


national_parks = {
    'Alaska':
        ['Denali',
        'Gates of the Arctic',
        'Glacier Bay',
        'Katmai',
        'Kenai Fjords',
        'Kobuk Valley',
        'Lake Clark',
        'Wrangell - St. Elias'],
    'Arizona':
        ['Saguaro',
        'Grand Canyon',
        'Petrified Forest'],
    'Arkansas':
        ['Hot Springs'],
    'California':
        ['Channel Islands',
        'Kings Canyon',
        'Lassen Volcanic',
        'Death Valley',
        'Joshua Tree',
        'Redwood',
        'Sequoia',
        'Yosemite',
        'Pinnacles'],
    'Colorado':
        ['Black Canyon of the Gunnison',
        'Great Sand Dunes',
        'Mesa Verde',
        'Rocky Mountain'],
    'Florida':
        ['Biscayne',
        'Dry Tortugas',
        'Everglades'],
    'Hawaii':
        ['Haleakala',
        'Hawaii Volcanoes'],
    'Indiana':
        ['Indiana Dunes'],
    'Idaho':
        ['Yellowstone'],
    'Montana':
        ['Yellowstone', 'Glacier'],
    'Wyoming':
        ['Yellowstone', 'Grand Teton'],
    'Kentucky':
        ['Mammoth Cave'],
    'Maine':
        ['Acadia'],
    'Michigan':
        ['Isle Royale'],
    'Minnesota':
        ['Voyageurs'],
    'Missouri':
        ['Gateway Arch'],
    'Nevada':
        ['Great Basin'],
    'New Mexico':
        ['Carlsbad Caverns',
        'White Sands'],
    'North Carolina':
        ['Great Smoky Mountains'],
    'North Dakota':
        ['Theodore Roosevelt'],
    'Ohio':
        ['Cuyahoga Valley'],
    'Oregon':
        ['Crater Lake'],
    'South Carolina':
        ['Congaree'],
    'South Dakota':
        ['Wind Cave',
        'Badlands'],
    'Tennessee':
        ['Great Smoky Mountains'],
    'Texas':
        ['Big Bend',
        'Guadalupe Mountains'],
    'Utah':
        ['Arches',
        'Capitol Reef',
        'Canyonlands',
        'Bryce Canyon',
        'Zion'],
    'Virginia':
        ['Shenandoah'],
    'Washington':
        ['Mount Rainier',
        'North Cascades',
        'Olympic'],
    'Alabama': [],
    'Connecticut': [],
    'Delaware': [],
    'Georgia': [],
    'Illinois': [],
    'Iowa': [],
    'Kansas': [],
    'Louisiana': [],
    'Maryland': [],
    'Massachuesetts': [],
    'Mississippi': [],
    'Nebraska': [],
    'New Hampshire': [],
    'New Jersey': [],
    'New York': [],
    'Oklahoma': [],
    'Pennsylvania': [],
    'Rhode Island': [],
    'Vermont': [],
    'Wisconsin': []
}

state_parks = {
    'Alabama':
        ['Blue Springs State Park',
        'Bucks Pocket State Park',
        'Cathedral Caverns State Park',
        'Cheaha State Park',
        'Chewacla State Park',
        'DeSoto State Park',
        'Frank Jackson State Park',
        'Gulf State Park',
        'Joe Wheeler State Park',
        'Lake Guntersville State Park',
        'Lake Lurleen State Park',
        'Lakepoint Resort State Park',
        'Meaher State Park',
        'Monte Sano State Park',
        'Oak Mountain State Park',
        'Rickwood Caverns State Park',
        'Wind Creek State Park'],
    'Alaska':
        ['Afognak Island State Park',
        'Alaska Chilkat Bald Eagle Preserve',
        'Anchor River State Recreation Area',
        'Baranof Castle State Historical Site',
        'Bettles Bay State Marine Park',
        'Big Delta State Historical Park',
        'Birch Lake (Alaska)',
        'Boswell Bay Beaches State Marine Park',
        'Caines Head State Recreation Area',
        'Captain Cook State Recreation Area',
        'Castle Hill (Sitka, Alaska)',
        'Chena River State Recreation Area',
        'Chilkat State Park',
        'Chilkoot Lake State Recreation Site',
        'Chugach State Park',
        'Decision Point State Marine Park',
        'Denali State Park',
        'Entry Cove State Marine Park',
        'Finger Lake (Alaska)',
        'Fort Abercrombie State Historical Park',
        'Grindall Island',
        'Ernest Gruening State Historical Park',
        'Harding Lake State Recreation Area',
        'Independence Mine State Historical Park',
        'Jack Bay State Marine Park',
        'Kachemak Bay State Park',
        'King Mountain State Recreation Site',
        'Lake Louise State Recreation Area',
        'Nancy Lake State Recreation Area',
        'Old Sitka Site',
        'Old Sitka State Historical Park',
        'Petroglyph Beach State Historic Park',
        'Quartz Lake State Recreation Area',
        'Shuyak Island State Park',
        'Squirrel Creek State Recreation Site',
        'Totem Bight State Historical Park',
        'Wood-Tikchik State Park',
        'Worthington Glacier State Recreation Site'],
    'Arizona':
        ['Alamo Lake State Park',
        'Buckskin Mountain State Park',
        'Catalina State Park',
        'Cattail Cove State Park',
        'Dead Horse Ranch State Park',
        'Fool Hollow Lake Recreation Area',
        'Fort Verde State Historic Park',
        'Granite Mountain Hotshots Memorial State Park',
        'Homolovi State Park',
        'Jerome State Historic Park',
        'Kartchner Caverns State Park',
        'Lake Havasu State Park',
        'Lost Dutchman State Park',
        'Lyman Lake State Park',
        'McFarland State Historic Park',
        'Oracle State Park',
        'Patagonia Lake State Park',
        'Picacho Peak State Park',
        'Red Rock State Park',
        'Riordan Mansion State Historic Park',
        'Roper Lake State Park',
        'San Rafael State Natural Area',
        'Slide Rock State Park',
        'Sonoita Creek State Natural Area',
        'Tombstone Courthouse State Historic Park',
        'Tonto Natural Bridge State Park',
        'Tubac Presidio State Historic Park',
        'Verde River Greenway State Natural Area',
        'Yuma Quartermaster Depot State Historic Park',
        'Yuma Territorial Prison State Historic Park'],
    'Arkansas':
        ['Arkansas Museum of Natural Resources',
        'Arkansas Post Museum',
        'Bull Shoals-White River State Park',
        'Cane Creek State Park',
        'Conway Cemetery State Park',
        'Cossatot River State Park-Natural Area',
        'Crater of Diamonds State Park',
        'Crowleys Ridge State Park',
        'Daisy State Park',
        'Davidsonville Historic State Park',
        'DeGray Lake Resort State Park',
        'Delta Heritage Trail State Park',
        'Devils Den State Park',
        'Hampson Archeological Museum State Park',
        'Herman Davis State Park',
        'Historic Washington State Park',
        'Hobbs State Park – Conservation Area',
        'Jacksonport State Park',
        'Jenkins Ferry Battleground State Park',
        'Lake Catherine State Park',
        'Lake Charles State Park',
        'Lake Chicot State Park',
        'Lake Dardanelle State Park',
        'Lake Fort Smith State Park',
        'Lake Frierson State Park',
        'Lake Ouachita State Park',
        'Lake Poinsett State Park',
        'Logoly State Park',
        'Louisiana Purchase State Park',
        'Lower White River Museum State Park',
        'Mammoth Spring State Park',
        'Marks Mills Battleground State Park',
        'Millwood State Park',
        'Mississippi River State Park',
        'Moro Bay State Park',
        'Mount Magazine State Park',
        'Mount Nebo State Park',
        'Ozark Folk Center State Park',
        'Parkin Archeological State Park',
        'Petit Jean State Park',
        'Pinnacle Mountain State Park',
        'Plantation Agriculture Museum',
        'Poison Springs Battleground State Park',
        'Powhatan Historic State Park',
        'Prairie Grove Battlefield State Park',
        'Queen Wilhelmina State Park',
        'South Arkansas Arboretum',
        'Toltec Mounds Archeological State Park',
        'Village Creek State Park',
        'White Oak Lake State Park',
        'Withrow Springs State Park',
        'Woolly Hollow State Park'],
    'California':
        ['Admiral William Standley State Recreation Area',
        'Ahjumawi Lava Springs State Park',
        'Albany State Marine Reserve',
        'Anderson Marsh State Historic Park',
        'Andrew Molera State Park',
        'Angel Island State Park',
        'Año Nuevo State Park',
        'Antelope Valley California Poppy Reserve',
        'Antelope Valley Indian Museum State Historic Park',
        'Anza-Borrego Desert State Park',
        'Armstrong Redwoods State Natural Reserve',
        'Arthur B. Ripley Desert Woodland State Park',
        'Asilomar State Beach',
        'Auburn State Recreation Area',
        'Austin Creek State Recreation Area',
        'Azalea State Natural Reserve',
        'Bale Grist Mill State Historic Park',
        'Bean Hollow State Beach',
        'Benbow Lake State Recreation Area',
        'Benicia Capitol State Historic Park',
        'Benicia State Recreation Area',
        'Bethany Reservoir State Recreation Area',
        'Bidwell Mansion State Historic Park',
        'Bidwell-Sacramento River State Park',
        'Big Basin Redwoods State Park',
        'Bodie State Historic Park',
        'Bolsa Chica State Beach',
        'Border Field State Park',
        'Bothe-Napa Valley State Park',
        'Brannan Island State Recreation Area',
        'Burleigh H. Murray Ranch',
        'Burton Creek State Park',
        'Butano State Park',
        'Butte City Project',
        'Calaveras Big Trees State Park',
        'California Citrus State Historic Park',
        'California Indian Heritage Center State Park (State Park)',
        'California State Capitol Museum',
        'California State Mining and Mineral Museum',
        'Cambria State Marine Park',
        'Candlestick Point State Recreation Area',
        'Cardiff State Beach',
        'Carlsbad State Beach',
        'Carmel River State Beach',
        'Carnegie State Vehicular Recreation Area',
        'Capitola State Beach',
        'Carpinteria State Beach',
        'Caspar Headlands State Beach',
        'Caspar Headlands State Natural Reserve',
        'Castaic Lake State Recreation Area',
        'Castle Crags State Park',
        'Castle Rock State Park',
        'Caswell Memorial State Park',
        'Cayucos State Beach',
        'China Camp State Park',
        'Chino Hills State Park',
        'Chumash Painted Cave State Historic Park',
        'Clay Pit State Vehicular Recreation Area',
        'Clear Lake State Park',
        'Colonel Allensworth State Historic Park',
        'Columbia State Historic Park',
        'Colusa-Sacramento River State Recreation Area',
        'Corona del Mar State Beach',
        'Crystal Cove State Park',
        'Cuyamaca Rancho State Park',
        'D. L. Bliss State Park',
        'Del Norte Coast Redwoods State Park',
        'Delta Meadows',
        'Dockweiler State Beach',
        'Doheny State Beach',
        'Donner Memorial State Park',
        'Ed Zberg Sugar Pine Point State Park',
        'El Capitán State Beach',
        'El Presidio de Santa Barbara State Historic Park',
        'Emerald Bay State Park',
        'Emeryville Crescent State Marine Reserve',
        'Emma Wood State Beach',
        'Empire Mine State Historic Park',
        'Estero Bluffs State Park',
        'Folsom Lake State Recreation Area',
        'Folsom Powerhouse State Historic Park',
        'The Forest of Nisene Marks State Park',
        'Fort Humboldt State Historic Park',
        'Fort Ord Dunes State Park',
        'Fort Ross State Historic Park',
        'Fort Tejon State Historic Park',
        'Franks Tract State Recreation Area',
        'Fremont Peak State Park',
        'Garrapata State Park',
        'Gaviota State Park',
        'George J. Hatfield State Recreation Area',
        'Governors Mansion State Historic Park',
        'Gray Whale Cove State Beach',
        'Great Valley Grasslands State Park',
        'Greenwood State Beach',
        'Grizzly Creek Redwoods State Park',
        'Grover Hot Springs State Park',
        'Half Moon Bay State Beach',
        'Harmony Headlands State Park',
        'Harry A. Merlo State Recreation Area',
        'Hatton Canyon',
        'Hearst San Simeon State Historical Monument',
        'Hearst San Simeon State Park',
        'Heber Dunes State Vehicular Recreation Area',
        'Hendy Woods State Park',
        'Henry Cowell Redwoods State Park',
        'Henry W. Coe State Park',
        'Hollister Hills State Vehicular Recreation Area',
        'Humboldt Lagoons State Park',
        'Humboldt Redwoods State Park',
        'Hungry Valley State Vehicular Recreation Area',
        'Huntington State Beach',
        'Indian Grinding Rock State Historic Park',
        'Indio Hills Palms',
        'Jack London State Historic Park',
        'Jedediah Smith Redwoods State Park',
        'John B. Dewitt Redwoods State Natural Reserve',
        'John Little State Natural Reserve',
        'Jug Handle State Natural Reserve',
        'Julia Pfeiffer Burns State Park',
        'Kenneth Hahn State Recreation Area',
        'Kings Beach State Recreation Area',
        'Kruse Rhododendron State Natural Reserve',
        'La Purísima Mission State Historic Park',
        'Lake Del Valle State Recreation Area',
        'Lake Oroville State Recreation Area',
        'Lake Perris State Recreation Area',
        'Lake Valley State Recreation Area',
        'Leland Stanford Mansion State Historic Park',
        'Leo Carrillo State Park',
        'Leucadia State Beach',
        'Lighthouse Field State Beach',
        'Limekiln State Park',
        'Little River State Beach',
        'Los Angeles State Historic Park',
        'Los Encinos State Historic Park',
        'Los Osos Oaks State Natural Reserve',
        'MacKerricher State Park',
        'Mailliard Woods State Natural Reserve',
        'Malakoff Diggins State Historic Park',
        'Malibu Creek State Park',
        'Malibu Lagoon State Beach',
        'Manchester State Park',
        'Mandalay State Beach',
        'Manresa State Beach',
        'Marconi Conference Center State Historic Park',
        'Marina State Beach',
        'Marsh Creek State Historic Park',
        'Marshall Gold Discovery State Historic Park',
        'Martial Cottle Park State Recreation Area',
        'McArthur-Burney Falls Memorial State Park',
        'McConnell State Recreation Area',
        'McGrath State Beach',
        'McLaughlin Eastshore State Park State Seashore',
        'Mendocino Headlands State Park',
        'Mendocino Woodlands State Park',
        'Millerton Lake State Recreation Area',
        'Mono Lake Tufa State Natural Reserve',
        'Montaña de Oro State Park',
        'Montara State Beach',
        'Monterey State Historic Park',
        'Monterey State Beach',
        'Montgomery Woods State Natural Reserve',
        'Moonlight State Beach',
        'Morro Bay State Park',
        'Morro Strand State Beach',
        'Moss Landing State Beach',
        'Mount Diablo State Park',
        'Mount San Jacinto State Park',
        'Mount Tamalpais State Park',
        'Natural Bridges State Beach',
        'Navarro River Redwoods State Park',
        'New Brighton State Beach',
        'Oceano Dunes State Vehicular Recreation Area',
        'Ocotillo Wells State Vehicular Recreation Area',
        'Old Sacramento State Historic Park',
        'Old Town San Diego State Historic Park',
        'Olompali State Historic Park',
        'Pacheco State Park',
        'Pacifica State Beach',
        'Palomar Mountain State Park',
        'Patricks Point  State Park',
        'Pelican State Beach',
        'Pescadero State Beach',
        'Petaluma Adobe State Historic Park',
        'Pfeiffer Big Sur State Park',
        'Picacho State Recreation Area',
        'Pigeon Point Light Station State Historic Park',
        'Pío Pico State Historic Park',
        'Pismo State Beach',
        'Placerita Canyon State Park',
        'Plumas-Eureka State Park',
        'Point Cabrillo Light Station State Historic Park',
        'Point Dume State Beach',
        'Point Lobos Ranch',
        'Point Lobos State Natural Reserve',
        'Point Mugu State Park',
        'Point Sal State Beach',
        'Point Sur State Historic Park',
        'Pomponio State Beach',
        'Portola Redwoods State Park',
        'Prairie City State Vehicular Recreation Area',
        'Prairie Creek Redwoods State Park',
        'Providence Mountains State Recreation Area',
        'Railtown 1897 State Historic Park',
        'Rancho San Andrés Castro Adobe',
        'Red Rock Canyon State Park',
        'Refugio State Beach',
        'Reynolds Wayside Campground',
        'Richardson Grove State Park',
        'Rio de Los Angeles State Park State Recreation Area',
        'Robert H. Meyer Memorial State Beach',
        'Robert Louis Stevenson State Park',
        'Robert W. Crown Memorial State Beach',
        'Russian Gulch State Park',
        'Saddleback Butte State Park',
        'Salinas River State Beach',
        'Salt Point State Park',
        'Salton Sea State Recreation Area',
        'Samuel P. Taylor State Park',
        'San Bruno Mountain State Park',
        'San Buenaventura State Beach',
        'San Clemente State Beach',
        'San Elijo State Beach',
        'San Gregorio State Beach',
        'San Juan Bautista State Historic Park',
        'San Luis Reservoir State Recreation Area',
        'San Onofre State Beach',
        'San Pasqual Battlefield State Historic Park',
        'San Timoteo Canyon',
        'Santa Cruz Mission State Historic Park',
        'Santa Monica State Beach',
        'Santa Susana Pass State Historic Park',
        'Schooner Gulch State Beach',
        'Seacliff State Beach',
        'Shasta State Historic Park',
        'Silver Strand State Beach',
        'Silverwood Lake State Recreation Area',
        'Sinkyone Wilderness State Park',
        'Smithe Redwoods State Natural Reserve',
        'Sonoma State Historic Park',
        'Sonoma Coast State Park',
        'South Carlsbad State Beach',
        'South Yuba River State Park',
        'Standish-Hickey State Recreation Area',
        'State Indian Museum',
        'Stone Lake',
        'Sugarloaf Ridge State Park',
        'Sunset State Beach',
        'Sutter Buttes State Park',
        'Sutters Fort State Historic Park',
        'Tahoe State Recreation Area',
        'Thornton State Beach',
        'Tijuana Estuary',
        'Tolowa Dunes State Park',
        'Tomales Bay State Park',
        'Tomo-Kahni State Historic Park',
        'Topanga State Park',
        'Torrey Pines State Beach',
        'Torrey Pines State Natural Reserve',
        'Trinidad State Beach',
        'Trione-Annadel State Park',
        'Tule Elk State Natural Reserve',
        'Turlock Lake State Recreation Area',
        'Twin Lakes State Beach',
        'Van Damme State Park',
        'Verdugo Mountains',
        'Ward Creek Project',
        'Washoe Meadows State Park',
        'Wassama Round House State Historic Park',
        'Watts Towers of Simon Rodia State Historic Park',
        'Weaverville Joss House State Historic Park',
        'Westport-Union Landing State Beach',
        'Wilder Ranch State Park',
        'Wildwood Canyon',
        'Will Rogers State Beach',
        'Will Rogers State Historic Park',
        'William B. Ide Adobe State Historic Park',
        'Woodland Opera House State Historic Park',
        'Woodson Bridge State Recreation Area',
        'Zmudowski State Beach'],
    'Colorado':
        ['Arkansas Headwaters Recreation Area',
        'Barr Lake State Park',
        'Boyd Lake State Park',
        'Castlewood Canyon State Park',
        'Chatfield State Park',
        'Cherry Creek State Park',
        'Cheyenne Mountain State Park',
        'Crawford State Park',
        'Eldorado Canyon State Park',
        'Eleven Mile State Park',
        'Elkhead Reservoir State Park',
        'Fishers Peak State Park',
        'Golden Gate Canyon State Park',
        'Harvey Gap State Park',
        'Highline Lake State Park',
        'Jackson Lake State Park',
        'James M. Robb - Colorado River State Park',
        'John Martin Reservoir State Park',
        'Lake Pueblo State Park',
        'Lathrop State Park',
        'Lone Mesa State Park',
        'Lory State Park',
        'Mancos State Park',
        'Mueller State Park',
        'Navajo State Park',
        'North Sterling State Park',
        'Paonia State Park',
        'Pearl Lake State Park',
        'Ridgway State Park',
        'Rifle Falls State Park',
        'Rifle Gap State Park',
        'Roxborough State Park',
        'Spinney Mountain State Park',
        'St. Vrain State Park',
        'Stagecoach State Park',
        'State Forest State Park',
        'Staunton State Park',
        'Steamboat Lake State Park',
        'Sweetwater Lake State Park',
        'Sweitzer Lake State Park',
        'Sylvan Lake State Park',
        'Trinidad Lake State Park',
        'Vega State Park',
        'Yampa River State Park'],
    'Connecticut':
        ['Above All State Park',
        'Auerfarm State Park Scenic Reserve',
        'Beaver Brook State Park',
        'Becket Hill State Park Reserve',
        'Beckley Furnace Industrial Monument',
        'Bennetts Pond State Park',
        'Bigelow Hollow State Park',
        'Black Rock State Park',
        'Bluff Point State Park',
        'Bolton Notch State Park',
        'Brainard Homestead State Park',
        'Burr Pond State Park',
        'Camp Columbia State Park/State Forest',
        'Campbell Falls State Park Reserve',
        'Chatfield Hollow State Park',
        'Collis P. Huntington State Park',
        'Connecticut Valley Railroad State Park',
        'Dart Island State Park',
        'Day Pond State Park',
        'Dennis Hill State Park',
        'Devils Hopyard State Park',
        'Dinosaur State Park',
        'Eagle Landing State Park',
        'Farm River State Park',
        'Ferry Landing State Park',
        'Fort Griswold Battlefield State Park',
        'Fort Trumbull State Park',
        'Gardner Lake State Park',
        'Gay City State Park',
        'George Dudley Seymour State Park',
        'George Waldo State Park',
        'Gillette Castle State Park',
        'Haddam Island State Park',
        'Haddam Meadows State Park',
        'Haley Farm State Park',
        'Hammonasset Beach State Park',
        'Harkness Memorial State Park',
        'Haystack Mountain State Park',
        'Higganum Reservoir State Park',
        'Hopemead State Park',
        'Hopeville Pond State Park',
        'Horse Guard State Park',
        'Housatonic Meadows State Park',
        'Humaston Brook State Park',
        'Hurd State Park',
        'Indian Well State Park',
        'John A. Minetto State Park',
        'Kent Falls State Park',
        'Kettletown State Park',
        'Killingly Pond State Park',
        'Lake Waramaug State Park',
        'Lamentation Mountain State Park',
        'Lovers Leap State Park',
        'Macedonia Brook State Park',
        'Machimoodus State Park',
        'Mansfield Hollow State Park',
        'Mashamoquet Brook State Park',
        'Mianus River State Park',
        'Millers Pond State Park',
        'Minnie Island State Park',
        'Mohawk Forest/Mohawk Mountain State Park',
        'Mono Pond State Park Reserve',
        'Mooween State Park',
        'Mount Bushnell State Park',
        'Mount Riga State Park',
        'Mount Tom State Park',
        'Nathaniel Lyon Memorial State Park',
        'Old Furnace State Park',
        'Osbornedale State Park',
        'Penwood State Park',
        'Platt Hill State Park',
        'Pomeroy State Park',
        'Putnam Memorial State Park',
        'Quaddick State Park',
        'Quinebaug Lake State Park',
        'Quinnipiac River State Park',
        'River Highlands State Park',
        'Rocky Glen State Park',
        'Rocky Neck State Park',
        'Ross Pond State Park',
        'Salt Rock State Campground',
        'Satans Kingdom State Recreation Area',
        'Scantic River State Park',
        'Selden Neck State Park',
        'Seth Low Pierrepont State Park Reserve',
        'Seaside State Park',
        'Sherwood Island State Park',
        'Silver Sands State Park',
        'Sleeping Giant State Park',
        'Southford Falls State Park',
        'Squantz Pond State Park',
        'Stillwater Pond State Park',
        'Stoddard Hill State Park',
        'Stratton Brook State Park',
        'Sunnybrook State Park',
        'Sunrise State Park',
        'Talcott Mountain State Park',
        'Tri-Mountain State Park',
        'Trout Brook Valley State Park Reserve',
        'Wadsworth Falls State Park',
        'West Rock Ridge State Park',
        'Wharton Brook State Park',
        'Whittemore Glen State Park',
        'Windsor Meadows State Park',
        'Wooster Mountain State Park'],
    'Delaware':
        ['Alapocas Run',
        'Auburn Valley',
        'Bellevue',
        'Brandywine Creek',
        'Cape Henlopen',
        'Delaware Seashore',
        'Fenwick Island',
        'First State Heritage',
        'Fort Delaware',
        'Fort DuPont',
        'Fox Point',
        'Holts Landing',
        'Killens Pond',
        'Lums Pond',
        'Trap Pond',
        'White Clay Creek',
        'Wilmington'],
    'Florida':
        ['Addison Blockhouse Historic State Park',
        'Alafia River State Park',
        'Alfred B. Maclay Gardens State Park',
        'Allen David Broussard Catfish Creek Preserve State Park',
        'Amelia Island State Park',
        'Anastasia State Park',
        'Anclote Key Preserve State Park',
        'Avalon State Park',
        'Bahia Honda State Park',
        'Bald Point State Park',
        'The Barnacle Historic State Park',
        'Big Lagoon State Park',
        'Big Shoals State Park',
        'Big Talbot Island State Park',
        'Bill Baggs Cape Florida State Park',
        'Blackwater River State Park',
        'Blue Spring State Park',
        'Bulow Creek State Park',
        'Bulow Plantation Ruins Historic State Park',
        'Caladesi Island State Park',
        'Camp Helen State Park',
        'Cayo Costa State Park',
        'Cedar Key Scrub State Reserve',
        'Cedar Key Museum State Park',
        'Charlotte Harbor Preserve State Park',
        'Collier-Seminole State Park',
        'Colt Creek State Park',
        'Constitution Convention Museum State Park',
        'Crystal River Archaeological State Park',
        'Crystal River Preserve State Park',
        'Curry Hammock State Park',
        'Dade Battlefield Historic State Park',
        'Dagny Johnson Key Largo Hammock Botanical State Park',
        'De Leon Springs State Park',
        'DeSoto Site Historic State Park',
        'Deer Lake State Park',
        'Delnor-Wiggins Pass State Park',
        'Devils Millhopper Geological State Park',
        'Don Pedro Island State Park',
        'Dr. Von D. Mizell-Eula Johnson State Park',
        'Dudley Farm Historic State Park',
        'Dunns Creek State Park',
        'Econfina River State Park',
        'Eden Gardens State Park',
        'Edward Ball Wakulla Springs State Park',
        'Egmont Key State Park',
        'Estero Bay Preserve State Park',
        'Fakahatchee Strand Preserve State Park',
        'Falling Waters State Park',
        'Fanning Springs State Park',
        'Faver-Dykes State Park',
        'Florida Caverns State Park',
        'Forest Capital Museum State Park',
        'Fort Clinch State Park',
        'Fort Cooper State Park',
        'Fort Foster State Historic Site',
        'Fort George Island Cultural State Park',
        'Fort Mose Historic State Park',
        'Fort Pierce Inlet State Park',
        'Fort Zachary Taylor Historic State Park',
        'Fred Gannon Rocky Bayou State Park',
        'Gainesville-Hawthorne State Trail',
        'Gamble Plantation Historic State Park',
        'Gamble Rogers Memorial State Recreation Area at Flagler Beach',
        'Gasparilla Island State Park',
        'George Crady Bridge Fishing Pier',
        'Gilchrist Blue Springs State Park',
        'Grayton Beach State Park',
        'Henderson Beach State Park',
        'Highlands Hammock State Park',
        'Hillsborough River State Park',
        'Homosassa Springs Wildlife State Park',
        'Honeymoon Island State Park',
        'Hontoon Island State Park',
        'Hugh Taylor Birch State Park',
        'Ichetucknee Springs State Park',
        'Indian Key Historic State Park',
        'John D. MacArthur Beach State Park',
        'John Gorrie Museum State Park',
        'John Pennekamp Coral Reef State Park',
        'Jonathan Dickinson State Park',
        'Kissimmee Prairie Preserve State Park',
        'Koreshan State Historic Site',
        'Lafayette Blue Springs State Park',
        'Lake Griffin State Park',
        'Lake Jackson Mounds Archaeological State Park',
        'Lake June in Winter Scrub State Park',
        'Lake Kissimmee State Park',
        'Lake Louisa State Park',
        'Lake Manatee State Park',
        'Lake Talquin State Park',
        'Letchworth-Love Mounds Archaeological State Park',
        'Lignumvitae Key Botanical State Park',
        'Little Manatee River State Park',
        'Little Talbot Island State Park',
        'Long Key State Park',
        'Lovers Key State Park',
        'Lower Wekiva River Preserve State Park',
        'Madira Bickel Mound State Archaeological Site',
        'Madison Blue Spring State Park',
        'Manatee Springs State Park',
        'Marjorie Kinnan Rawlings Historic State Park',
        'Mike Roess Gold Head Branch State Park',
        'Mound Key Archaeological State Park',
        'Myakka River State Park',
        'Natural Bridge Battlefield Historic State Park',
        'North Peninsula State Park',
        'Okeechobee Battlefield State Park',
        'OLeno State Park',
        'Ochlockonee River State Park',
        'Oleta River State Park',
        'Olustee Battlefield Historic State Park',
        'Orman House Historic State Park',
        'Oscar Scherer State Park',
        'Paynes Creek Historic State Park',
        'Paynes Prairie Preserve State Park',
        'Perdido Key State Park',
        'Prices Scrub State Park',
        'Ponce de Leon Springs State Park',
        'Pumpkin Hill Creek Preserve State Park',
        'Rainbow Springs State Park',
        'Ravine Gardens State Park',
        'River Rise Preserve State Park',
        'Rock Springs Run State Reserve',
        'San Felasco Hammock Preserve State Park',
        'San Marcos de Apalache Historic State Park',
        'San Pedro Underwater Archaeological Preserve State Park',
        'Savannas Preserve State Park',
        'Seabranch Preserve State Park',
        'Sebastian Inlet State Park',
        'Silver Springs State Park',
        'Skyway Fishing Pier State Park',
        'St. Andrews State Park',
        'St. George Island State Park',
        'St. Lucie Inlet Preserve State Park',
        'St. Marks River Preserve State Park',
        'St. Sebastian River Preserve State Park',
        'Stephen Foster Folk Culture Center State Park',
        'Stump Pass Beach State Park',
        'Suwannee River State Park',
        'T.H. Stone Memorial St. Joseph Peninsula State Park',
        'Tarkiln Bayou Preserve State Park',
        'Terra Ceia Preserve State Park',
        'Three Rivers State Park',
        'Tomoka State Park',
        'Topsail Hill Preserve State Park',
        'Torreya State Park',
        'Troy Spring State Park',
        'Waccasassa Bay Preserve State Park',
        'Washington Oaks Gardens State Park',
        'Weeki Wachee Springs',
        'Wekiwa Springs State Park',
        'Werner-Boyce Salt Springs State Park',
        'Wes Skiles Peacock Springs State Park',
        'Windley Key Fossil Reef Geological State Park',
        'Ybor City Museum State Park',
        'Yellow Bluff Fort Historic State Park',
        'Yellow River Marsh Preserve State Park',
        'Yulee Sugar Mill Ruins Historic State Park'],
    'Georgia':
        ['A.H. Stephens State Park',
        'Amicalola Falls State Park & Lodge',
        'Black Rock Mountain State Park',
        'Chattahoochee Bend State Park[3]',
        'Cloudland Canyon State Park',
        'Crooked River State Park',
        'Don Carter State Park[1]',
        'Elijah Clark State Park',
        'F. D. Roosevelt State Park',
        'Florence Marina State Park',
        'Fort McAllister State Park',
        'Fort Mountain State Park',
        'Fort Yargo State Park',
        'General Coffee State Park',
        'George L. Smith State Park',
        'George T. Bagby State Park',
        'Georgia Veterans State Park',
        'Gordonia-Alatamaha State Park',
        'Hamburg State Park',
        'Hard Labor Creek State Park',
        'Hart State Outdoor Recreation Area',
        'High Falls State Park',
        'Indian Springs State Park',
        'James H. Floyd State Park',
        'Kolomoki Mounds State Park',
        'Laura S. Walker State Park',
        'Little Ocmulgee State Park & Lodge',
        'Magnolia Springs State Park',
        'Mistletoe State Park',
        'Moccasin Creek State Park',
        'Panola Mountain State Park',
        'Providence Canyon State Outdoor Recreation Area',
        'Red Top Mountain State Park',
        'Reed Bingham State Park',
        'Richard B. Russell State Park',
        'Seminole State Park',
        'Skidaway Island State Park',
        'Smithgall Woods State Park',
        'Stephen C. Foster State Park',
        'Sweetwater Creek State Park',
        'Tallulah Gorge State Park',
        'Tugaloo State Park',
        'Unicoi State Park & Lodge',
        'Victoria Bryant State Park',
        'Vogel State Park',
        'Watson Mill Bridge State Park'],
    'Hawaii': [],
    'Idaho': [],
    'Illinois': [],
    'Indiana': [],
    'Iowa': [],
    'Kansas': [],
    'Kentucky': [],
    'Louisiana': [],
    'Maine': [],
    'Maryland': [],
    'Massachusetts': [],
    'Michigan': [],
    'Minnesota': [],
    'Mississippi': [],
    'Missouri': [],
    'Montana': [],
    'Nebraska': [],
    'Nevada': [],
    'New Hampshire': [],
    'New Jersey': [],
    'New Mexico': [],
    'New York': [],
    'North Carolina': [],
    'North Dakota': [],
    'Ohio': [],
    'Oklahoma': [],
    'Oregon': [],
    'PennsylvaniaRhode Island': [],
    'South Carolina': [],
    'South Dakota': [],
    'Tennessee': [],
    'Texas': [],
    'Utah': [],
    'Vermont': [],
    'Virginia': [],
    'Washington': [],
    'West Virginia': [],
    'Wisconsin': [],
    'Wyoming': []
}

major_cities = {
    'Alabama':
        [],
    'Alaska':
        ['Juneau'],
    'Arizona':
        ['Phoenix', 'Flagstaff'],
    'Arkansas':
        ['Little Rock'],
    'California':
        ['San Francisco', 'San Diego', 'Los Angeles'],
    'Colorado':
        ['Denver'],
    'Connecticut':
        ['Hartford'],
    'Delaware':
        ['Dover'],
    'Florida': ['Miami'],
    'Georgia': ['Atlanta'],
    'Hawaii': [],
    'Idaho': [],
    'Illinois': ['Chicago'],
    'Indiana': [],
    'Iowa': [],
    'Kansas': [],
    'Kentucky': [],
    'Louisiana': ['New Orleans'],
    'Maine': [],
    'Maryland': [],
    'Massachusetts': ['Boston'],
    'Michigan': ['Detroit'],
    'Minnesota': ['Minneapolis', 'St Paul'],
    'Mississippi': [],
    'Missouri': [],
    'Montana': [],
    'Nebraska': [],
    'Nevada': [],
    'New Hampshire': [],
    'New Jersey': [],
    'New Mexico': [],
    'New York': [],
    'North Carolina': [],
    'North Dakota': [],
    'Ohio': [],
    'Oklahoma': [],
    'Oregon': [],
    'Pennsylvania': [],
    'Rhode Island': [],
    'South Carolina': [],
    'South Dakota': [],
    'Tennessee': [],
    'Texas': [],
    'Utah': ['Salt Lake City'],
    'Vermont': [],
    'Virginia': [],
    'Washington': ['Seattle'],
    'West Virginia': [],
    'Wisconsin': [],
    'Wyoming': []
}

current_state = ""

def tasks(request):
    current_state = ""
    if request.method == 'POST':
        # this is wehere POST request is accessed
        current_state = request.POST.get('textfield')
        return render(request, 'tasks.html', {'national_parks': national_parks, 'state_parks': state_parks, 'major_cities': major_cities, 'current_state': current_state})
    return render(request, 'tasks.html', {'national_parks': national_parks, 'state_parks': state_parks, 'major_cities': major_cities, 'current_state': current_state})
